# Site setings
name: "zulloper's Blog"
description: 'Security Engineer'
meta_description: '-'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'author_image.png'
  greetings: "Hi there! My name is zulloper. I'm a security engineer. It’s nice to meet you."
favicon: 'assets/images/favicon.ico'
baseurl: ''
production_url: ''
disqus: 'zulloper-github-io'
mailchimp_url: ''
# Add your GA Tracking Id
ga_analytics: 'UA-103585557-1'

# Contact form setings
email: zulloper@email.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'y6eqwYrZByEugro'
#facebook: ''
github: 'zulloper'
#codepen: ''
#dribbble: ''
#medium: ''
#instagram: ''
#pinterest: ''
#linkedin: ''
#producthunt: ''
#quora: ''

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
#  - text: Style Guide
#    url: /style-guide
#  - text: Contact Me
#    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
